CourseWebDeveloper/Controllers/BeneficiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseWebDeveloper.Controllers
{
    public class BeneficiosController : Controller
    {
        //
        // GET: /Beneficios/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CourseWebDeveloper/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseWebDeveloper.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CourseWebDeveloper/Controllers/RestauranteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CourseWebDeveloper.Controllers
{
    public class RestauranteController : Controller
    {
        //
        // GET: /Restaurante/
        public ActionResult Index()
        {
            return View();
        }
	}
}

CourseWebDeveloper/Views/Beneficios/Index.cshtml
@{
    ViewBag.Title = "Benefícios";
}

<a id="topo"><h1>Benefícios</h1></a>

<a href="@Url.Action("Index", "Home")">Voltar</a>

<ul>
    <li>Embraco</li>
    <li>Unilever</li>
    <li>Grupo Boticário</li>
    <li><a href="#google">Google</a></li>
    <li><a href="#brooksfield">brookfield incorporações</a></li>
    <li>Uniqlo</li>
    <li><a href="#link1">Link1</a></li>
    <li><a href="#link2">Link2</a></li>
</ul>

<h2>Embraco</h2>
<p>
    Desde 1991, a Embraco, fabricante de compressores para refrigeração, mantém um berçário dentro da fábrica em Joinville, SC.
    O espaço é voltado para crianças de até um ano e com 25 vagas. Para as mulheres o benefício é gratuito.
    A funcionária pode começar a trabalhar 30 minutos mais tarde para amamentar o filho, atividade que realiza de novo no meio do dia e no
    final do expediente, quando é liberada 20 minutos mais cedo.
</p>

<h2>Unilever</h2>
<p>
    Entre as vantagens para os 13.700 colaboradores no Brasil, a Unilever oferece um programa de mentoria.
    O funcionário escolhe seu mentor, que recebe uma capacitação para esse papel.
    Os programas de aconselhamento e desenvolvimento ajudam o profissional a crescer ascensão de cargo dentro da Unilever ou que foram
    promovidos recentemente.
</p>

<h2>Grupo Boticário</h2>
<p>
    Cerca de 70% dos 7.000 colaboradores diretos do Grupo Boticário são mulheres.
    Por isso, a empresa - que engloba as marcas O Boticário, Eudora, quem disse, berenice? e The Beauty Box - oferece diversos benefícios para mulheres,
    gestantes e mães.
</p>

<a id="google"><h3>Google</h3></a>
<p>
    O Google é reconhecido pelas regalias que oferece a seus funcionários.
    Em quase todas as sedes da empresa de tecnologia, a geladeira é aberta e funcionários podem pegar os lanchinhos que quiserem, de forma gratuita.
</p>

<a id="brooksfield"><h3>Brookfield Incorporações</h3></a>
<p>
    Para diminuir o estresse e garantir o bem-estar físico e psicológico dos seus funcionários, a Brookfield Incorporações oferece o programa Fique Bem.
    Com assessoria jurídica, financeira, social e psicológica, o programa existe desde 2009 e é confidencial, sem passar pelo RH da empresa.<br />
    <a href="#topo">Voltar ao topo</a>
</p>

<h3>Uniqlo</h3>
<p>
    Para a rede japonesa de moda Uniqlo, a semana de trabalho tem apenas quatro dias.
    A empresa irá propor a seus funcionários três dias de folga, para aumentar o convívio familiar.
    O sistema, que deve vigorar a partir de outubro, não terá redução salarial, mas prevê um aumento do período diário de trabalho de 8 para 10 horas.
    <br />
    <a href="#topo">Voltar ao topo</a>
</p>

<h2>Grupo Boticário</h2>
<p>
    Cerca de 70% dos 7.000 colaboradores diretos do Grupo Boticário são mulheres.
    Por isso, a empresa - que engloba as marcas O Boticário, Eudora, quem disse, berenice? e The Beauty Box - oferece diversos benefícios para mulheres,
    gestantes e mães.
</p>

<a id="link1"><h3>Link1</h3></a>
<p>
    O Google é reconhecido pelas regalias que oferece a seus funcionários.
    Em quase todas as sedes da empresa de tecnologia, a geladeira é aberta e funcionários podem pegar os lanchinhos que quiserem, de forma gratuita.
</p>

<a id="link2"><h3>Link2</h3></a>
<p>
    Para diminuir o estresse e garantir o bem-estar físico e psicológico dos seus funcionários, a Brookfield Incorporações oferece o programa Fique Bem.
    Com assessoria jurídica, financeira, social e psicológica, o programa existe desde 2009 e é confidencial, sem passar pelo RH da empresa.<br />
    <a href="#topo">Voltar ao topo</a>
</p>

<h3>Uniqlo</h3>
<p>
    Para a rede japonesa de moda Uniqlo, a semana de trabalho tem apenas quatro dias.
    A empresa irá propor a seus funcionários três dias de folga, para aumentar o convívio familiar.
    O sistema, que deve vigorar a partir de outubro, não terá redução salarial, mas prevê um aumento do período diário de trabalho de 8 para 10 horas.
    <br />
    <a href="#topo">Voltar ao topo</a>
</p>

CourseWebDeveloper/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1 align="center" style="color: rgb(255, 78, 26);">Lorem Ipsum</h1>
<hr />
<h3 align="center" style="color: #2F4F4F;">Lorem ipsum dolor sit amet, consectetur adipiscing elit</h3>

@*  method post = envia as informações pelo servidor
    method get =  envia as informações via url

    controles utilizados em formulários *@
<form action="@Url.Action("Index", "Home")" method="get">
    
    <fieldset>
        <legend>Informações Pessoais</legend>

        <label for="nome">Nome:</label><input type="text" id="nome" value="Internauta" tabindex="1" /><br />

        <label for="sexo">Sexo:</label><br />
        <input type="radio" name="sexo" id="sexo" value="M" />Masculino<br />
        <input type="radio" name="sexo" id="sexo" value="M" />Feminino<br />

        <label for="senha">
            Senha:
            <input type="password" id="senha" /><br />
        </label>
    </fieldset>

    <fieldset>
        <legend>Informações Profissionais</legend>

        <label for="conhecimentos">Conhecimentos:</label><br />
        <input type="checkbox" name="conhecimentos" id="conhecimentos" value="Java" />Java<br />
        <input type="checkbox" name="conhecimentos" id="conhecimentos" value="Html" />Html<br />
        <input type="checkbox" name="conhecimentos" id="conhecimentos" value="css" />css<br />
        <input type="checkbox" name="conhecimentos" id="conhecimentos" value="xslt" />xslt<br />

        Currículo:<br />
        <input type="file" id="curriculo" /><br />

        <input type="submit" value="Enviar" /><br />
        <input type="reset" value="Limpar" /><br />
        <input type="button" value="Validar Formulário" /><br />

        <label for="resumo">Resumo:</label><br />
        <textarea cols="40" rows="6" id="resumo">Escreva seu resumo aqui</textarea><br />

    </fieldset>

    <fieldset>
        <legend>Outras Informações</legend>

        País:<br />
        <select id="pais">
            <option>Brasil</option>
            <option>Espanha</option>
            <option>EUA</option>
            <option>Japão</option>
            <option>Suíça</option>
        </select><br />

        Editores ou Navegadores:<br />
        <select id="en">
            <optgroup label="Editores">
                <option>Notepad++</option>
                <option>DreamWeaver</option>
                <option>Eclipse</option>
                <option>HTML-Kit</option>
            </optgroup>
            <optgroup label="Navegadores">
                <option>Firefox</option>
                <option>IE</option>
                <option>Safari</option>
                <option>Opera</option>
            </optgroup>
        </select>
    </fieldset>
</form>

<p style="text-align: center;">
    <img src="~/Assets/images/IMG_9596.jpg" style="width: 200px;" alt="Visão Torre de TV" />
    <a href="http://www.congressonacional.leg.br" target="_blank" style="border: 0px;" alt="Acesso Congresso Nacional" title="Congresso Nacional"><img src="~/Assets/images/IMG_9625.jpg" style="width: 200px;" alt="Congresso Nacional" /></a>
    <img src="~/Assets/images/IMG_9693.jpg" style="width: 200px;" alt="Visão Pontão do Lago" />
</p>

<p style="color: rgb(49, 97, 111);">
    Ut tristique magna <b>Lorem Ipsum  (tag b)</b> vitae lorem iaculis ultricies. Sed fringilla dolor ac ornare ultricies.
    Nullam convallis arcu quis quam volutpat, sit amet varius justo laoreet. Pellentesque dignissim tellus et nunc semper ultricies.
    Nullam sollicitudin tristique felis in tempus. Nunc sit amet erat diam. Maecenas pellentesque est finibus ipsum semper mollis.
</p>

<blockquote>
    Integer vel metus id justo eleifend porttitor. Quisque aliquet neque in tellus <i>(ullamcorper bibendum  (tag i))</i>.
    Aenean tempus eu leo ac luctus. Suspendisse at sollicitudin sem. In hac habitasse platea dictumst.
    Aenean pellentesque aliquam ante, in molestie erat viverra vitae. Donec a tellus bibendum, <tt>facilisis (tag tt)</tt> massa sit amet, fermentum nisi.
    Nam vitae enim consequat, dignissim eros mollis, volutpat lorem. Vestibulum sagittis ac <a href="http://www.r7.com" target="_blank">Portal R7 (tag a)</a>. Fusce at lacinia quam.
</blockquote>

<pre>
    Este
        Documento
            está
                Pré
                    Formatado
    (tag pre)
</pre>

<p>
    Praesent <u>sollicitudin (tag u)</u> consectetur est, quis semper enim vulputate pulvinar.
    Sed et nisi tortor. Praesent eget nisl neque. Maecenas dignissim ipsum ut bibendum pharetra.
    Suspendisse pretium velit eu rutrum elementum. Etiam tincidunt
    <del>augue non (tag del)</del> lacinia convallis.
    Mauris nec gravida mauris, quis pulvinar mi. Mauris felis lorem,
    <a href="@Url.Action("Index", "Beneficios")">benefícios da empresa</a>,
    volutpat pulvinar risus.
    Etiam non tincidunt sem. Morbi ex sapien, suscipit vel ante vel, aliquet vulputate nibh.
    Sed condimentum arcu lectus, laoreet volutpat turpis congue quis.
</p>

<p>
    <img src="~/Assets/images/dolar.jpg" alt="Dollar" align="right" style="width: 200px;" />
</p>

<p>
    <b>Lista Não Ordenada</b>
    <ul>
        <li>Abertura de Conta</li>
        <li>Contratação de Plano</li>
        <li>Mudança de Plano</li>
        <li>Contratação de Seguro Auto</li>
        <li>Aplicação Financeira</li>
        <li>Pesquisa e Desenvolvimento</li>
        <li>@Html.ActionLink("Intercambio Cultural", "Index", "Beneficios")</li>
        <li><a href="@Url.Action("Index", "Beneficios")">Google</a></li>
        <li>Treinamento Gerencial</li>
    </ul>

    <b>Lista Ordenada</b>
    <ol>
        <li>Abertura de Conta</li>
        <li>Contratação de Plano</li>
        <li>Mudança de Plano</li>
        <li>Contratação de Seguro Auto</li>
        <li>Aplicação Financeira</li>
        <li>Pesquisa e Desenvolvimento</li>
        <li>intercambio Cultural</li>
        <li>Oportunidades</li>
        <li>Treinamento Gerencial</li>
    </ol>

    <b>Lista de Definição</b>
    <dl>
        <dt>Tecnologia</dt>
        <dd>Ferramentas e as máquinas que ajudam a resolver problemas</dd>
        <dd>Estudo dos instrumentos, processos e métodos empregados</dd>
        <dt>Internet</dt>
        <dd>Rede telamática internacional que une computadores</dd>
        <dt>Software</dt>
        <dd>Conjunto de instruções armazenadas em disco(s) ou chips</dd>
    </dl>

    <b>Lista Mista</b>
    <ol>
        <li>
            Spider
            <ul>
                <li>Ferari 360 Spider</li>
                <li>BMW Z4</li>
            </ul>
        </li>
        <li>
            Berlinetta
            <ul>
                <li>Ferrari Dino</li>
                <li>Lamborguini Miura</li>
            </ul>
        </li>
        <li>
            Cabriolet
            <ul>
                <li>Peugeot 307</li>
                <li>BMW Serie</li>
                <li>Renault Megane</li>
            </ul>
        </li>
    </ol>
</p>

<p>
    <div>Texto</div>

    Cras id porta dolor, quis fringilla tellus. Nulla blandit congue mi et sollicitudin.
    Integer tempor massa eget nibh pellentesque, nec sollicitudin diam placerat.
    Vestibulum ante ipsum primis in <em title="empresa">Empresa</em> faucibus orci luctus et ultrices posuere cubilia Curae; <em>Aenean euismod sem a lorem convallis, id tempus mauris tempus (tag em)</em>.
    Nullam eu pulvinar felis. <big>Curabitur (tag big)</big> venenatis arcu arcu, vel <small>vulputate (tag small)</small> mauris laoreet non.
    Donec posuere nulla felis, sit amet viverra mauris tempor a. Aliquam ac turpis sollicitudin, sollicitudin eros in, hendrerit justo.
    Aliquam nec lorem in ex dictum tempus. Nunc tincidunt, purus at egestas porta, felis sem aliquet justo, id iaculis arcu metus eu velit.
    Suspendisse venenatis sagittis lobortis. Etiam elementum turpis nec consequat tempus.
    Integer nisl eros, sagittis non eros in, placerat dignissim quam.
</p>

<p class="destaque">
    @*<div id="introducao">Texto</div>*@

    Cras id porta dolor, quis fringilla tellus. Nulla blandit congue mi et sollicitudin.
    Integer tempor massa eget nibh pellentesque, nec sollicitudin diam placerat.
    Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; <em>Aenean euismod sem a lorem convallis, id tempus mauris tempus (tag em)</em>.
    Nullam eu pulvinar felis. <big>Curabitur (tag big)</big> venenatis arcu arcu, vel <small>vulputate (tag small)</small> mauris laoreet non.
    Donec posuere nulla felis, sit amet viverra mauris tempor a. Aliquam ac turpis sollicitudin, sollicitudin eros in, hendrerit justo.
    Aliquam nec lorem in ex dictum tempus. Nunc tincidunt, purus at egestas porta, felis sem aliquet justo, id iaculis arcu metus eu velit.
    Suspendisse venenatis sagittis lobortis. Etiam elementum turpis nec consequat tempus.
    Integer nisl eros, sagittis non eros in, placerat dignissim quam.
</p>

<p style="text-align: center;">
    <b>Utilizando a tag map para criar um link em uma área específica</b>
</p>

<p style="text-align: center;">

    <img src="~/Assets/images/mapa-brasil.jpg" usemap="#brasil" alt="mapa-brasil" />
    <img src="~/Assets/images/futebol.jpg" usemap="#futebol" alt="futebol" />

    <map name="brasil">
        <area shape="rect" coords="282,238,304,259" href="http://www.brasilia.df.gov.br" target="_blank" alt="Brasília" />
        <area shape="poly" coords="145,164,143,190,163,191,155,220,161,249,180,249,188,267,234,270,262,211,265,177,195,171,180,146,178,164" href="http://www.mt.gov.br" target="_blank" alt="Mato Grosso" />
    </map>

    <map name="futebol">
        <area shape="circle" coords="345,126,80" href="#" alt="futebol" />
    </map>
</p>

<p>
    Utilizando Tabelas
    <table border="1" cellpadding="20" cellspacing="0">
        <tr>
            <td>Unidade</td>
            <td>Dia</td>
            <td style="background-color:#CCCCCC;">Treinamento</td>
            <td>Instrutor</td>
        </tr>
        <tr>
            <td rowspan="2">Brasília</td>
            <td>2</td>
            <td align="left">Sorum</td>
            <td rowspan="2">Aman</td>
        </tr>
        <tr>
            <td>12</td>
            <td align="left">Java</td>
        </tr>
        <tr>
            <td>São Paulo</td>
            <td>3</td>
            <td align="center">Lumis</td>
            <td>Jeosadache</td>
        </tr>
        <tr>
            <td>Rio de Janeiro</td>
            <td>3</td>
            <td align="justify">HTML</td>
            <td>Esaú</td>
        </tr>
    </table>
</p>

<p>
    <h3>Links de Envio de Mensagens e Chamadas Telefônicas</h3>
    Envio de Email = <a href="mailto:P534722@mail.caixa?cc=P941155@mail.caixa&subject=Duvidas&body=Qual o prazo de atendimento">Email</a><br />
    Chamada Telefonica = <a href="callto:+556139012500">Telefone</a><br />
    Ligação Skype = <a href="skype:cristianoSilva?call">Skype Call</a><br />
    Chat Skype = <a href="skype:cristianoSilva?chat">Skype Chat</a><br />
    Ligação Gtalk = <a href="gtalk:call?jid=yourscreenname">GTalk Call</a><br />
    Chat Gtalk = <a href="gtalk:chat?jid=yourscreenname">GTalk Chat</a><br />
    Chat MSN Messenger = <a href="msnim:chat?contact=yourscreenname">Chat MSN Messenger</a><br />
    Yahoo Messenger = <a href="ymsgr:sendim?yourscreenname">Yahoo! Messenger</a><br />
    AOL Messenger = <a href="aim:goim?screenname=yourscreenname">AOL Messenger</a>
</p>

<address align="center">
    Diretamente de Brasília,<br />
    S<sup>r. (tag sup)</sup> Cristiano Silva<br />
    www.site.com.br | cristdf@gmail.com<br />
    2<sup>ª (tag sup)</sup> Feira | <q>Beba <sub>H</sub>2<sub>O (tag sub)</sub> durante os estudos!</q>(tag q)<br />
</address>

@*
    O site W3C apresenta vários elementos html
    O site W3Schools.com
    Editores de imagem www.imagemagick.com

    <u> deixa o texto sublinhado
    <em> ênfase
    <strong> ênfase mais forte
    <del> indica que o trecho está sendo excluído
    <tt> define todas as leras com a mesma largura. texto com fonte teletipo
    <sup> marca a letra para cima
    <sub> marca a letra para baixo
    <q> indica uma citação de uma linha
    <blockquote> é uma citação em bloco
    <pre> mantém a formação da mesma forma que foi digitado no código fonte, preserva toda a forma
    <big> coloca o texto um pouco maior que o resto do texto
    <small> coloca o texto um pouco menos que o resto do texto


*@

CourseWebDeveloper/Views/Restaurante/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Restaurante</h1>

<a href="@Url.Action("Index", "Home")">Voltar</a>

<div style="width: 250px; background-color: #cccccc; float: left;">
    <h2>Comidas</h2>

    <p><img src="~/Assets/images/picanha.jpg" /></p>
    <h3>Churrasco</h3>
    <p>
        Não há <span style="color:green;">churrasco</span> igual ao feito no Rio Grande do Sul – pelo menos segundo os gaúchos.
        Os mais tradicionalistas abominam rodízio (ou espeto corrido) e torcem o nariz para bufê de salada.
        Para eles, a farinha de mandioca é a melhor companhia para a carne.
        Também não têm interesse pelo filé-mignon - suas preferências são a costela e a picanha.
        Muitas churrascarias de Porto Alegre servem, à la carte, carnes de boi, porco, carneiro e galeto no espeto, temperadas só com sal grosso,
        que impede o ressecamento e garante sabor e macies.
    </p>

    <p><img src="~/Assets/images/carne-de-sol.jpg" /></p>
    <h3>Carne de Sol</h3>
    <p>
        Um banquete de carne de sol inclui sempre feijão-verde, macaxeira, farofa dágua, pirão de leite e vinagrete.
        Mas não se deixe enganar pelo nome do ingrediente principal: a carne salgada descansa previamente na geladeira ou em câmara fria,
        e não no sol, que a deixaria mais dura e desidratada, originando a famosa carne-seca.
        Extraída de coxão mole ou duro, a peça é assada na grelha ou frita na manteiga de garrafa.
    </p>

    <p><img src="~/Assets/images/acaraje.jpg" /></p>
    <h3>Acarajé</h3>
    <p>
        Chamado de acará na língua iorubá, o bolinho de feijão-fradinho, frito em azeite de dendê, é recheado com vatapá,
        camarão seco e vinagrete. Paladares desacostumados devem responder "Não" à pergunta "Com pimenta?", repetida pelas baianas nas barracas
        de Salvador. As melhores ficam no Farol da Barra, e costumam aparecer por lá à noitinha. Quem prepara: as baianas em suas barracas.
        As mais famosas são de Dinha e de Regina (Largo de Santana, Rio Vermelho), de Cira (Largo de Itapuã, em Itapuã, e Largo da Mariquita,
        no Rio Vermelho) e de Sônia (Farol da Barra).
    </p>
</div>

<div style="width: 250px; float: left;">
    <h2>Bebidas</h2>

    <p><img src="~/Assets/images/Martini-Rosso.jpg" /></p>
    <h3>Martini Rosso</h3>
    <p>
        Bebida composta de vinho tinto e ervas aromáticas. Criado inicialmente em 1863, Martini Rosso permanece como o autêntico vermute: natural,
        elegante, refrescante e estimulante. Pode ser encontrado ainda nas versões bianco e rosé e é ideal para ser servido como aperitivo com
        gelo picado, ou misturado com sucos de frutas ou água mineral.
    </p>

    <p><img src="~/Assets/images/Punt-Mes.jpg" /></p>
    <h3>Punt e Mes</h3>
    <p>
        Surge em Turim, Itália, e traz, no sabor levemente amargo, uma receita secreta que combina a destilação de uvas misturadas com substâncias
        balsâmicas e aromáticas, que caracterizam um bom vermute. Ótimo se apreciado em copo longo com gelo, água tônica e rodelas de laranja.
    </p>

    <p><img src="~/Assets/images/Baileys.jpg" /></p>
    <h3>Baileys</h3>
    <p>
        Licor irlandês elaborado a partir da mistura de creme de leite irlandês com o melhor whisky do país e sabores naturais de cacau e baunilha.
        Esses ingredientes são misturados utilizando os mais modernos equipamentos em um processo que, apesar de simples, é altamente secreto.
    </p>

    <p><img src="~/Assets/images/Cointreau.jpg" /></p>
    <h3>Cointreau</h3>
    <p>
        Licor fino, elaborado a partir de um blend de cascas de laranjas doces e amargas em um processo controlado.
        As laranjas utilizadas para a sua elaboração vêm de todas as partes do mundo, especialmente do Brasil e dos Estados Unidos.
        Além de ser consumido como digestivo e aperitivo, também é muito utilizado na culinária.
    </p>
</div>

CourseWebDeveloper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Course Web Developer</title>

    <!--REFERÊNCIA CSS-->
    <link href="~/Assets/css/estilo.css" rel="stylesheet" />
</head>
<body style="background-color: #ffffff;">
    
    <div class="container body-content">
        @RenderBody()
    </div>
</body>
</html>